apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      imagePullSecrets:
        - name: rd-registry
      containers:
        - name: ecommerce
          image: tiktzuki/ecommerce:latest
          ports:
            - name: rpc
              containerPort: 9090
              protocol: TCP
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
          envFrom:
            - configMapRef:
                name: ecommerce-config