apiVersion: v1
kind: Service
metadata:
  name: ecommerce
  labels:
    app: ecommerce
spec:
  type: LoadBalancer
  selector:
    app: ecommerce
  ports:
    - protocol: TCP
      port: 8080
      name: http